name: index_manager
description: This package manages multiple indexes identified by name and supports serialization and deserialization.
version: 0.0.2
repository: https://github.com/MasahideMori-SimpleAppli/index_manager

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
